language: ruby
rvm:
- 2.2
#- 2.1
#- 2.0
- 1.9.3
env:
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=centos:7
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=debian:8
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=fedora:20
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=fedora:24
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=ubuntu:12.04
- ANSIBLE_VERSIONS=1.4 DOCKER_IMAGES=ubuntu:18.04
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=centos:7
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=debian:8
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=fedora:20
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=fedora:24
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=ubuntu:12.04
- ANSIBLE_VERSIONS=1.5.4 DOCKER_IMAGES=ubuntu:18.04
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=centos:7
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=debian:8
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=fedora:20
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=fedora:24
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=ubuntu:12.04
- ANSIBLE_VERSIONS=1.9.2 DOCKER_IMAGES=ubuntu:18.04
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=centos:7
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=debian:8
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=fedora:20
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=fedora:24
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=ubuntu:12.04
- ANSIBLE_VERSIONS=2.1.0.0 DOCKER_IMAGES=ubuntu:18.04
services:
- docker
script:
- wget -O- bit.ly/ansibletest | sh -x
after_failure:
- cat role-tester-ansible-master/.kitchen.yml
- cat role-tester-ansible-master/.kitchen.local.yml
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: change
    on_failure: change
    rooms:
      - secure: Ik1yq73B4KNEJixrNRv45/W/HuFOlGkInlom7ffWR0tV64LItJ+ZsNxauCn2NylzP8ggwfjGYKEez5b8foLSZmLAAZUyKNDZl0024SVqwMTqbFo9vI35mhyUExhIhBvCY/qSTmIri+jWNPcALCApbP3hnuTfwLuBuIxXQMxj0x/TTwyr43odllo3+xiejV+6/GdgvPHlE3H8GR1dLYRG2zym7BnyGeFexH/CKv0xHMORwk9TjkV4Ky9wUIIy2nn/D32Z8zUzeWCoo/xNeenMdrZHwerEuCyWRz5sIymtyavJqMsEkfIzXWPRCKOgg1xp1V0Y6t8LBNaBwAqdE4oQkZaWTJBt6lW0uoPdmYzrJwRdqjzlPg5kSH9L9556+Q5JCTzrOg1HBOZR0oj+DOdJw9iJ5k3Vo3pyGCod24tSfPuQ8A9599ZMV7+n1GGdJtVsj27i5+FOMBHLXOJwcxn0BMMw5/GkiCvGLbNAlMNm9ZCW3oYPZL2p1JR3EJvVTXmtWSV44HSJiqzcg0pza9LIzO0fbmWL4HOhSDFJQwJgtR7SlMaUjv0a1HDBS2FI+xJxFCb0pKzBmwQSs9gSV5XrfV2Pfj4sfz9eyHklCCvPldmX0xuK94+hB5xeXZBJdWhdRJxINFiwBqlRZAxpmfpUfXECN2O00+n8bEX1FMpCzKU=
  email:
    recipients:
      secure: sM1SmAPkc/pkeJ6qfsf+KolxvKC4fiSjQmMo6IN+9nan+/nTm6oNnVEPNckIFqSfkfOx3GBKmexlr03GKAas5Wqow3dQVkeKJcIcfjpFwYnGWSMsaxKDwnE25lnUC8a3kjYNUeuFdeA2GTiejdOZ5myQ95iMYU4KZqozfVjmt5KKjCADUoN9PtwdN8GLiKor+jNE0ZlpdJ5WOwavsgGCBeOzprsTtJrovSytiJ6CYlgr1EpP8OMmrr7sRJfdVO0QRYWzgh6JfkTsMCn+wR9qjF3kGYZJZtYiJD3F/V8X8uui3yLHdBwmATbWRLTed1RO+5/7vCX8Xf5ZDVmhH2dRiHCkUg9zqReNFkC+W57iZa6LUdkvjJIx3Iuj8MUYduabQyF2FLO7Xx84nlSQeQdx1YE4b3ayM8nx2vT3A1+gXco0M4P0UbWAAyPRofx9Hr6h6sMNtKyG6qrHhgSUHcUSXq5HpoUtYhEFiv/hXOu9lEzyvJXuOaWK2jdxNyqPT2yYadj64dp+3k6vMisFHU3RSUKWrvx/Di5KgnC6vkf0udq+H1H+n0s0ppSPlu3G0ZzZs0KA6AA+zsjZDvd/eow3CDFC8v2RBtOg3r21x6KjqM+owlPFgKpbz/aK3mU1bdf2J8ZMVWbWkNf7kkAmnZJ6PoeSUIbLhxmPBpnNNqxSvu8=
