---
- name: check for short-circuit
  raw: "> /dev/null command -v alex"
  register: installed
  ignore_errors: True
  changed_when: False

- name: check-for-short-circuit
  set_fact:
    should_run: "{{installed|failed or not alex_should_shortcircuit}}"

- include: include_vars.yml

- include: sudoorbecome.yml
